### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by michaelcarter** [holidayextras/generator-webapp-view#1]
- Readme should be specific on where these are intended to be used. From what I understand they’re for use within the project template repo? If this isn’t the case, what advantages does it give over just "git cloning" a barebones repo. I expect people are more familiar with the git clone workflow...

 - Naming seems the wrong way around to me, `generator-app-module` instead of `app-module-generator`. I'm not a huge fan of the `app-module` naming convention we've managed to get going either. I think it’s not descriptive enough . These are specifically shared views right? Not generic modules.

 - Prefer pluralised directory names, e.g. `styles`, `templates` and `views`.

**Comment by lukehansell-hx** [comment]
Regarding the first point:
There should be no reason why this generator can't be used either inside an existing project or as a stand alone resource. I could even add a flag to the prompt which specifies building the dev site or not. That way we just end up with the code directory (or even better the contents of the code directory). 

The advantages over "git cloning" are primarily the ability to rename the files and exports as they are generated (which makes the renaming easier for the user as files don't get missed) and if we extend this any further we can also add dynamic functionality to these which isn't available in clones (such as building alternative brands during generation). Ultimately this was the path that Mark and I agreed upon when I began working on this.

Regarding the second point:
I agree with you that the naming seems backwards, however this is the convention for yeoman generators. 

Also, I agree with the naming issue for "app-module". I think we should each come up with some alternatives and compile a list and pick the best as at the moment we're saying we don't like it, but not providing hard alternatives.

Regarding your third point: I'll change these now :smile:

**Comment by lukehansell-hx** [comment]
Tasks from feedback:
* Included in this work:
  * renaming to generator-webapp-view and changing app-module to webapp-view
* New PR:
  * [extending to include non-shared views](https://holidayextras.jira.com/browse/TAR-197)

**Comment by lukehansell-hx** [comment]
Resolved in https://github.com/holidayextras/generator-webapp-view/pull/2
